type Playlist @aws_iam @aws_cognito_user_pools {
  name: String!
  description: String
  coverImageUrl: String
  tracks: String
  trackCount: Int
  totalDuration: Int
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  id: ID!
}

type Track @aws_iam @aws_cognito_user_pools {
  artist: String
  title: String!
  version: String
  label: String
  genre: String
  year: Int
  duration: Int
  fileUrl: String
  fileSize: Int
  format: String
  addedAt: AWSDateTime
  bpm: Int
  key: String
  energy: Float
  danceability: Float
  valence: Float
  coverArtUrl: String
  waveformUrl: String
  peaks: String
  trimStart: Float
  trimEnd: Float
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

input AmplifyAIConversationTurnErrorInput {
  errorType: String!
  message: String!
}

input ModelStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelBooleanInput {
  ne: Boolean
  eq: Boolean
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelSubscriptionStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  in: [String]
  notIn: [String]
}

input ModelSubscriptionIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  in: [Int]
  notIn: [Int]
}

input ModelSubscriptionFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  in: [Float]
  notIn: [Float]
}

input ModelSubscriptionBooleanInput {
  ne: Boolean
  eq: Boolean
}

input ModelSubscriptionIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  in: [ID]
  notIn: [ID]
}

enum ModelAttributeTypes {
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
  _null
}

input ModelSizeInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
}

enum ModelSortDirection {
  ASC
  DESC
}

type ModelPlaylistConnection @aws_iam @aws_cognito_user_pools {
  items: [Playlist]!
  nextToken: String
}

input ModelPlaylistFilterInput {
  name: ModelStringInput
  description: ModelStringInput
  coverImageUrl: ModelStringInput
  tracks: ModelStringInput
  trackCount: ModelIntInput
  totalDuration: ModelIntInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  id: ModelIDInput
  and: [ModelPlaylistFilterInput]
  or: [ModelPlaylistFilterInput]
  not: ModelPlaylistFilterInput
}

type Query {
  getPlaylist(id: ID!): Playlist @aws_iam @aws_cognito_user_pools
  listPlaylists(filter: ModelPlaylistFilterInput, limit: Int, nextToken: String): ModelPlaylistConnection @aws_iam @aws_cognito_user_pools
  getTrack(id: ID!): Track @aws_iam @aws_cognito_user_pools
  listTracks(filter: ModelTrackFilterInput, limit: Int, nextToken: String): ModelTrackConnection @aws_iam @aws_cognito_user_pools
}

input ModelPlaylistConditionInput {
  name: ModelStringInput
  description: ModelStringInput
  coverImageUrl: ModelStringInput
  tracks: ModelStringInput
  trackCount: ModelIntInput
  totalDuration: ModelIntInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelPlaylistConditionInput]
  or: [ModelPlaylistConditionInput]
  not: ModelPlaylistConditionInput
}

input CreatePlaylistInput {
  name: String!
  description: String
  coverImageUrl: String
  tracks: String
  trackCount: Int
  totalDuration: Int
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  id: ID
}

input UpdatePlaylistInput {
  name: String
  description: String
  coverImageUrl: String
  tracks: String
  trackCount: Int
  totalDuration: Int
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  id: ID!
}

input DeletePlaylistInput {
  id: ID!
}

type Mutation {
  createPlaylist(input: CreatePlaylistInput!, condition: ModelPlaylistConditionInput): Playlist @aws_iam @aws_cognito_user_pools
  updatePlaylist(input: UpdatePlaylistInput!, condition: ModelPlaylistConditionInput): Playlist @aws_iam @aws_cognito_user_pools
  deletePlaylist(input: DeletePlaylistInput!, condition: ModelPlaylistConditionInput): Playlist @aws_iam @aws_cognito_user_pools
  createTrack(input: CreateTrackInput!, condition: ModelTrackConditionInput): Track @aws_iam @aws_cognito_user_pools
  updateTrack(input: UpdateTrackInput!, condition: ModelTrackConditionInput): Track @aws_iam @aws_cognito_user_pools
  deleteTrack(input: DeleteTrackInput!, condition: ModelTrackConditionInput): Track @aws_iam @aws_cognito_user_pools
}

input ModelSubscriptionPlaylistFilterInput {
  name: ModelSubscriptionStringInput
  description: ModelSubscriptionStringInput
  coverImageUrl: ModelSubscriptionStringInput
  tracks: ModelSubscriptionStringInput
  trackCount: ModelSubscriptionIntInput
  totalDuration: ModelSubscriptionIntInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  and: [ModelSubscriptionPlaylistFilterInput]
  or: [ModelSubscriptionPlaylistFilterInput]
}

type Subscription {
  onCreatePlaylist(filter: ModelSubscriptionPlaylistFilterInput): Playlist @aws_subscribe(mutations: ["createPlaylist"]) @aws_iam @aws_cognito_user_pools
  onUpdatePlaylist(filter: ModelSubscriptionPlaylistFilterInput): Playlist @aws_subscribe(mutations: ["updatePlaylist"]) @aws_iam @aws_cognito_user_pools
  onDeletePlaylist(filter: ModelSubscriptionPlaylistFilterInput): Playlist @aws_subscribe(mutations: ["deletePlaylist"]) @aws_iam @aws_cognito_user_pools
  onCreateTrack(filter: ModelSubscriptionTrackFilterInput): Track @aws_subscribe(mutations: ["createTrack"]) @aws_iam @aws_cognito_user_pools
  onUpdateTrack(filter: ModelSubscriptionTrackFilterInput): Track @aws_subscribe(mutations: ["updateTrack"]) @aws_iam @aws_cognito_user_pools
  onDeleteTrack(filter: ModelSubscriptionTrackFilterInput): Track @aws_subscribe(mutations: ["deleteTrack"]) @aws_iam @aws_cognito_user_pools
}

type ModelTrackConnection @aws_iam @aws_cognito_user_pools {
  items: [Track]!
  nextToken: String
}

input ModelTrackFilterInput {
  artist: ModelStringInput
  title: ModelStringInput
  version: ModelStringInput
  label: ModelStringInput
  genre: ModelStringInput
  year: ModelIntInput
  duration: ModelIntInput
  fileUrl: ModelStringInput
  fileSize: ModelIntInput
  format: ModelStringInput
  addedAt: ModelStringInput
  bpm: ModelIntInput
  key: ModelStringInput
  energy: ModelFloatInput
  danceability: ModelFloatInput
  valence: ModelFloatInput
  coverArtUrl: ModelStringInput
  waveformUrl: ModelStringInput
  peaks: ModelStringInput
  trimStart: ModelFloatInput
  trimEnd: ModelFloatInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelTrackFilterInput]
  or: [ModelTrackFilterInput]
  not: ModelTrackFilterInput
}

input ModelTrackConditionInput {
  artist: ModelStringInput
  title: ModelStringInput
  version: ModelStringInput
  label: ModelStringInput
  genre: ModelStringInput
  year: ModelIntInput
  duration: ModelIntInput
  fileUrl: ModelStringInput
  fileSize: ModelIntInput
  format: ModelStringInput
  addedAt: ModelStringInput
  bpm: ModelIntInput
  key: ModelStringInput
  energy: ModelFloatInput
  danceability: ModelFloatInput
  valence: ModelFloatInput
  coverArtUrl: ModelStringInput
  waveformUrl: ModelStringInput
  peaks: ModelStringInput
  trimStart: ModelFloatInput
  trimEnd: ModelFloatInput
  and: [ModelTrackConditionInput]
  or: [ModelTrackConditionInput]
  not: ModelTrackConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreateTrackInput {
  artist: String
  title: String!
  version: String
  label: String
  genre: String
  year: Int
  duration: Int
  fileUrl: String
  fileSize: Int
  format: String
  addedAt: AWSDateTime
  bpm: Int
  key: String
  energy: Float
  danceability: Float
  valence: Float
  coverArtUrl: String
  waveformUrl: String
  peaks: String
  trimStart: Float
  trimEnd: Float
  id: ID
}

input UpdateTrackInput {
  artist: String
  title: String
  version: String
  label: String
  genre: String
  year: Int
  duration: Int
  fileUrl: String
  fileSize: Int
  format: String
  addedAt: AWSDateTime
  bpm: Int
  key: String
  energy: Float
  danceability: Float
  valence: Float
  coverArtUrl: String
  waveformUrl: String
  peaks: String
  trimStart: Float
  trimEnd: Float
  id: ID!
}

input DeleteTrackInput {
  id: ID!
}

input ModelSubscriptionTrackFilterInput {
  artist: ModelSubscriptionStringInput
  title: ModelSubscriptionStringInput
  version: ModelSubscriptionStringInput
  label: ModelSubscriptionStringInput
  genre: ModelSubscriptionStringInput
  year: ModelSubscriptionIntInput
  duration: ModelSubscriptionIntInput
  fileUrl: ModelSubscriptionStringInput
  fileSize: ModelSubscriptionIntInput
  format: ModelSubscriptionStringInput
  addedAt: ModelSubscriptionStringInput
  bpm: ModelSubscriptionIntInput
  key: ModelSubscriptionStringInput
  energy: ModelSubscriptionFloatInput
  danceability: ModelSubscriptionFloatInput
  valence: ModelSubscriptionFloatInput
  coverArtUrl: ModelSubscriptionStringInput
  waveformUrl: ModelSubscriptionStringInput
  peaks: ModelSubscriptionStringInput
  trimStart: ModelSubscriptionFloatInput
  trimEnd: ModelSubscriptionFloatInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionTrackFilterInput]
  or: [ModelSubscriptionTrackFilterInput]
}
